/* eslint-disable @next/next/no-img-element */
import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'

function About() {
  return (
    <>
      <Head>
        <title>What is Medium?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <main>
        <div className="border-y-2 border-black w-full">
          <div className="max-w-3xl mx-auto flex justify-between items-center px-5 py-10">
            <h1 className='text-3xl md:text-5xl flex-1'>Every idea needs a</h1>
            <img src="/wordmark.svg" alt="" />
          </div>
        </div>
        <div className='w-full bg-black h-fit'>
            <div className='flex flex-col md:flex-row text-white'>
                <div className='flex-1 flex items-center justify-center py-6 text-3xl md:text-5xl'>
                    <h1 className='text-center font-bold'>Over 100 million readers and growing.</h1>
                </div>
                <div className='flex flex-col items-center flex-1 py-6 md:border-l-2'>
                    <img className='w-32 h-32 object-cover' src="/user1.png" alt="" />
                    <h1 className='p-10'>There is no other place that combines such an excellent level of writing with a truly engaged and active community. Medium is truly where ideas are born, shared, and spread.</h1>
                    <h2>Jackie Colburn</h2>
                </div>
            </div>
            <div className='flex flex-col items-center text-white border-t-2 p-10 leading-8'>
                <h1 className='text-5xl font-bold text-center my-4'>Create the space for your thinking to take off.</h1>
                <p>A blank page is also a door. At Medium you can walk through it. It is easy and free to share your thinking on any topic, connect with an audience, express yourself with a range of publishing tools, and even earn money for your work.</p>
                <button className='text-green-500 px-5 py-3 border border-green-500 rounded-full my-4 font-bold hover:text-white hover:bg-green-500 ease-in-out duration-200'>Write on Medium</button>
            </div>
        </div>
        <div className='border-t-2 bg-black text-white w-full'>
            <div className='max-w-xl mx-auto flex items-center justify-around p-5'>
                <h1 className='cursor-pointer font-bold hover:underline'>Terms</h1>
                <h1 className='cursor-pointer font-bold hover:underline'>Privacy</h1>
                <h1 className='cursor-pointer font-bold hover:underline'>Help</h1>
            </div>
        </div>
      </main>
    </>
  )
}

export default About
