/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Post from '../components/Post'

import { sanityClient, urlFor } from '../sanity'
import { PostProps } from '../typings'

interface Props {
  posts: [PostProps]
}

const Home = ({ posts }: Props) => {
  return (
    <div className="max-w-6xl mx-auto">
      <Head>
        <title>Medium Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Header />
      <Hero />      

      <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 p-3 gap-3 md:gap-6 md:px-0'>
        {posts.map(({ slug, _id, mainImage, author, title, description }) => (
          <Post
            key={_id}
            slug={slug}
            mainImage={mainImage}
            title={title}
            description={description}
            author={author}
          />
        ))}
      </div>
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = `*[_type == 'post']{
    _id,
    title,
    slug,
    author -> {
     name,
    image,
  },
  description,
  mainImage,
  }`

  const posts = await sanityClient.fetch(query)

  return {
    props: {
      posts,
    },
  }
}

export default Home
